name: Feature Request
description: Suggest a feature or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        > **Please search both open and closed issues before submitting a new one to avoid duplication**

  - type: dropdown
    id: new
    validations:
      required: true
    attributes:
      label: Is this a new feature?
      default: 0
      multiple: false
      options:
        - "No"
        - "Yes"

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Please describe your feature request
      description: A clear and concise description about the feature.
      placeholder: e.g., Add feature X.

  - type: textarea
    validations:
      required: true
    attributes:
      label: Please provide the purpose of the feature
      description: A clear and concise explanation about the feature purpose.
      placeholder: e.g., This will help users do X.

  - type: textarea
    id: notes
    validations:
      required: false
    attributes:
      label: Additional notes
      description: Any other information that might help.
