name: Documentation Update
description: Suggest an update or addition to the documentation.
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        > **Please search both open and closed issues before submitting a new one to avoid duplication**

  - type: dropdown
    id: addition
    validations:
      required: true
    attributes:
      label: Is this addition?
      description: Select "Yes" if this is an addition.
      default: 0
      multiple: false
      options:
        - "No"
        - "Yes"

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Please explain what should be added or changed
      description: Describe the update or addition.
      placeholder: e.g., Add an example for the X function.

  - type: textarea
    id: notes
    validations:
      required: false
    attributes:
      label: Additional notes
      description: Any other information that might help.
