name: Others
description: Others issue
labels: [others]
body:
  - type: markdown
    attributes:
      value: |
        > **Please search both open and closed issues before submitting a new one to avoid duplication**

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Please describe your issue
