name: Others
description: Others issue
title: "[OTHERS] <title>"
labels: ["others", "Needs Triage"]
body:
  - type: markdown
    attributes:
      value: |
        > Please search open and closed issues before submitting a new one.<br/>Existing issues might contain information about workarounds or resolutions.

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Please describe your issue
