name: Labeler

on:
  pull_request_target:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  label:
    name: Add label
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2
        with:
          egress-policy: audit

      - name: Labeler action
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
