name: PR Title

on:
  pull_request:
    branches:
      - "*"
    types:
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  title:
    name: PR Title check
    runs-on: ubuntu-24.04
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            bun.sh:443
            github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443

      - name: Git checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          sparse-checkout: .

      - name: Set up bun@latest
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1

      - name: Install dependencies
        run: bun ci

      - name: Run check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: printenv "PR_TITLE" | bunx --bun commitlint
