name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    name: Publish release
    if: github.repository == 'itsmeid/release-example-002'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            bun.sh:443
            github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
            tuf-repo-cdn.sigstore.dev:443
            uploads.github.com:443

      - name: Git checkout (full-history)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up bun@latest
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1

      - name: Install dependencies
        run: bun ci

      - name: Run check
        run: bun check

      - name: Audit signatures
        run: bunx npm audit signatures

      - name: Build dist
        run: bunx tsc -p ./tsconfig.dist.json

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bunx npx semantic-release && cat CHANGELOG.md >> $GITHUB_STEP_SUMMARY
