name: Reviewdog

run-name: Reviewdog > ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  review-format:
    name: Review format
    if: ${{ github.actor != 'renovate[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2
        with:
          egress-policy: audit

      - name: Git checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Review code
        uses: mongolyy/reviewdog-action-biome@aed3609ddbb255fb7be62299245943d9cdda3225 # v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: false
